default: &default
  adapter: postgres
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: rnacademy_dev
  pool: 3
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: rnacademy_test
  pool: 5
  password: root

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
